###### README
# For all code segments, please run the code segments IN ORDER to produce the results as discussed in report

In [181]:
# importing packages
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from scipy.spatial.distance import cdist

In [182]:
# loading files
train = pd.read_csv('train_dataset.csv')
test = pd.read_csv('test_dataset.csv')

In [183]:
# spliting data to dependent and independent variables
train = train.sample(frac=1).reset_index(drop=True)
train_x = train.drop('imdb_score_binned', axis=1)
rating = train['imdb_score_binned']

In [184]:
# swapping test data to preprepared npy data to files
actor_1_name = np.load('test_countvec_features_actor_1_name.npy')
actor_2_name = np.load('test_countvec_features_actor_2_name.npy')
director_name = np.load('test_countvec_features_director_name.npy')
genres = np.load('test_doc2vec_features_genre.npy')
plot_keywords = np.load('test_doc2vec_features_plot_keywords.npy')
title = np.load('test_fasttext_title_embeddings.npy')

swap_list = [actor_1_name, actor_2_name, director_name, genres, plot_keywords, title]

names = ['actor_1_name', 'actor_2_name', 'director_name', 'genres', 'plot_keywords', 'title_embedding']
test_processed = test.copy()
for i in range(len(test_swap_list)):
    test_processed[names[i]] = swap_list[i]
    
test_processed

,id,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,plot_keywords,num_user_for_reviews,language,country,content_rating,title_year,actor_2_facebook_likes,movie_facebook_likes,title_embedding,average_degree_centrality
0,1,0,27,118,14,400,0,2000,2246000,0.001098,...,0.004658,20,English,USA,PG,2015,769,0,-0.001873,0.000375
1,2,0,339,141,0,404,0,749,47307550,-0.000351,...,-0.004515,269,English,USA,R,2012,463,28000,-0.000913,0.002176
2,3,0,78,95,89,388,0,963,37606,0.001212,...,-0.003206,90,English,Canada,R,2009,654,0,-0.000221,0.000900
3,4,0,226,117,0,818,0,15000,104054514,-0.000348,...,0.004929,1009,English,USA,R,2002,1000,0,-0.000780,0.003452
4,5,0,97,104,38,690,0,801,3447339,-0.000994,...,-0.004458,79,English,USA,R,2013,727,0,-0.002775,0.000450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
747,748,0,179,93,0,766,0,13000,17096053,-0.002793,...,0.001449,640,English,USA,R,1998,933,5000,0.001090,0.002777
748,749,0,393,105,335,911,0,3000,37516013,-0.004198,...,0.000414,348,English,USA,R,2012,3000,98000,-0.001081,0.001801
749,750,0,55,117,133,249,0,687,20966644,0.003380,...,0.004388,94,English,UK,Unrated,1985,443,0,-0.003145,0.001126
750,751,0,85,72,0,384,0,3000,47887943,0.003230,...,0.000964,58,English,USA,G,2003,455,227,-0.004907,0.000825
751,752,0,35,87,4,624,0,2000,19539,-0.002372,...,0.001755,53,English,USA,R,2003,1000,3000,-0.003787,0.002401

In [185]:
# swapping train data to preprepared npy data to files
genres = np.load('train_doc2vec_features_genre.npy')
plot_keywords = np.load('train_doc2vec_features_plot_keywords.npy')
title = np.load('train_fasttext_title_embeddings.npy')
actor_1_name = np.load('train_countvec_features_actor_1_name.npy')
actor_2_name =  np.load('train_countvec_features_actor_2_name.npy')
director_name =  np.load('train_countvec_features_director_name.npy')

swap_list = [actor_1_name, actor_2_name, director_name, genres, plot_keywords, title]
train_x_processed = train_x.copy()
for i in range(len(test_swap_list)):
    train_x_processed[names[i]] = swap_list[i]
    
train_x_processed

,id,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,plot_keywords,num_user_for_reviews,language,country,content_rating,title_year,actor_2_facebook_likes,movie_facebook_likes,title_embedding,average_degree_centrality
0,544,0,39,109,9,280,0,767,3050934,0.003078,...,-0.002800,78,English,USA,PG-13,2000,380,0,-0.004198,0.000600
1,2419,0,274,148,0,826,0,17000,18352454,0.001751,...,0.002123,760,English,USA,R,2007,882,76000,-0.004759,0.002026
2,159,0,120,109,0,126,0,3000,3798532,-0.003030,...,-0.002241,208,English,USA,R,1996,441,2000,0.002781,0.001276
3,1636,0,114,164,17000,159,0,883,8373585,0.004092,...,-0.000630,308,English,USA,R,1988,618,0,-0.005327,0.002401
4,1127,0,97,125,0,957,0,10000,48154732,-0.004901,...,-0.002958,142,English,USA,R,1997,2000,2000,-0.004259,0.004277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,683,0,488,126,584,398,0,11000,4563029,-0.000862,...,-0.004451,514,English,South Korea,R,2013,557,58000,-0.002348,0.001426
3000,27,0,62,117,101,743,0,13000,24944213,-0.002787,...,-0.002579,185,English,USA,PG-13,1996,852,3000,0.001623,0.003602
3001,7,0,37,99,675,164,0,902,418953,-0.000343,...,-0.004208,93,English,France,R,1993,424,853,-0.001068,0.000825
3002,947,0,262,92,87,424,0,15000,58401464,-0.000772,...,-0.002913,264,English,USA,PG-13,2010,1000,19000,-0.001281,0.001576
3003,1278,0,59,150,3,448,0,859,6157157,-0.002789,...,-0.002065,198,English,USA,PG-13,1989,448,0,-0.001727,0.000450

In [186]:
# filling unrated content rating by using euclidean distance of the plot keywords doc2vec values
def infer_content_rating(df):
    """
    Output the assigned file filling all the unrated entries by finding the content rating inferring from
    plot keywords using euclidean distance.
    """   
    remove_missing = df.copy()
    # Find rows with missing content ratings
    missing_rows = df[(df['content_rating'] == 'Not Rated') | (df['content_rating'] == 'Unrated')]
    remove_missing = remove_missing.drop(missing_rows.index)
    plot_keywords = np.array(remove_missing['plot_keywords'])
    float_value = 0.323324
    distances = np.abs(plot_keywords - float_value)
    return distances

infer_content_rating(train_x_processed)

array([0.3261245 , 0.32120052, 0.32556525, ..., 0.32753235, 0.32623672,
       0.32538918], dtype=float32)

In [187]:
# filling unrated content rating by comparing euclidean distance of the plot keywords doc2vec values
def infer_content_rating(df):
    """
    Output the assigned file filling all the unrated entries by finding the content rating inferring from
    plot keywords using euclidean distance.
    """   
    remove_missing = df.copy()
    missing_rows = df[(df['content_rating'] == 'Not Rated') | (df['content_rating'] == 'Unrated')]
    remove_missing = remove_missing.drop(missing_rows.index)
    plot_keywords = np.array(remove_missing['plot_keywords'])
    for index, row in missing_rows.iterrows():
        distances = np.abs(plot_keywords - row['plot_keywords'])
        closest_index = distances.argmin()
        inferred_rating = df.iloc[closest_index]['content_rating']
        df.at[index, 'content_rating'] = inferred_rating  
    return df

infer_content_rating(train_x_processed)
infer_content_rating(test_processed)
train_x['content_rating'] = train_x_processed['content_rating']
test['content_rating'] = test_processed['content_rating']

In [188]:
# conducting one hot encoding to language, country, actor3 names and content rating for both training and test 
# data for models that cannot process non- numerical data

def one_hot_encoding(parameter, file):
    """
    return the input file converting the assigned parameter to an array by one hot encoding
    """
    encoder = OneHotEncoder()
    array = np.array(file[parameter]).reshape(-1, 1)
    encoded = encoder.fit_transform(array)
    onehot_array = encoded.toarray()
    file[parameter]= onehot_array.tolist()
    return file

names = ['language', 'actor_3_name', 'country', 'content_rating']
for i in names:
    one_hot_encoding(i, train_x_processed)
    one_hot_encoding(i, test_processed)
    
train_x_processed

,id,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,plot_keywords,num_user_for_reviews,language,country,content_rating,title_year,actor_2_facebook_likes,movie_facebook_likes,title_embedding,average_degree_centrality
0,544,0,39,109,9,280,0,767,3050934,0.003078,...,-0.002800,78,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",2000,380,0,-0.004198,0.000600
1,2419,0,274,148,0,826,0,17000,18352454,0.001751,...,0.002123,760,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",2007,882,76000,-0.004759,0.002026
2,159,0,120,109,0,126,0,3000,3798532,-0.003030,...,-0.002241,208,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1996,441,2000,0.002781,0.001276
3,1636,0,114,164,17000,159,0,883,8373585,0.004092,...,-0.000630,308,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1988,618,0,-0.005327,0.002401
4,1127,0,97,125,0,957,0,10000,48154732,-0.004901,...,-0.002958,142,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1997,2000,2000,-0.004259,0.004277
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2999,683,0,488,126,584,398,0,11000,4563029,-0.000862,...,-0.004451,514,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",2013,557,58000,-0.002348,0.001426
3000,27,0,62,117,101,743,0,13000,24944213,-0.002787,...,-0.002579,185,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",1996,852,3000,0.001623,0.003602
3001,7,0,37,99,675,164,0,902,418953,-0.000343,...,-0.004208,93,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1993,424,853,-0.001068,0.000825
3002,947,0,262,92,87,424,0,15000,58401464,-0.000772,...,-0.002913,264,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",2010,1000,19000,-0.001281,0.001576
3003,1278,0,59,150,3,448,0,859,6157157,-0.002789,...,-0.002065,198,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, ...",1989,448,0,-0.001727,0.000450

In [175]:
# problem left unsolved
# note that the movie title is the only non- processed data that is non- numerical